name: Scala CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Formatting
      working-directory: sdram_controller_gen
      run: sbt scalafmt
    - name: Check Formatting
      working-directory: sdram_controller_gen
      run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
    - name: Run tests
      working-directory: sdram_controller_gen
      run: sbt test